void main(List<String>args) {
  List<dynamic> donemselBilgiVerme =[
    "1.Ay Gebelik: Bu dönemde embriyo hızla büyürken organ sistemleri gelişir.Doktorunuzla düzenli olarak randevular ayarlayarak gebeliğinizi doğrulatmalısınız.",
    "2.Ay Gebelik: Prenatal vitaminlerinizi düzenli olarak kullanmalısınız.Sağlıklı beslenmeye dikkat etmelisiniz, özellikle folik asit içeren gıdalar tüketmelisiniz. ",
    "3.Ay Gebelik: Sigara, alkol ve uyuşturucu maddelerden uzak durmalısınız.Cinsel ilişkide bulunurken doktorunuzun önerilerini takip etmelisiniz.Düzenli egzersiz yapmalı, aşırı fiziksel aktivitelerden kaçınmalısınız.",
    "4.Ay Gebelik: Bebek hareketleri bu dönemde hissedilebilir hale gelir.Rutin prenatal kontrollerinizi düzenli olarak sürdürmelisiniz.",
    "5.Ay Gebelik: Doğru uyku pozisyonlarına dikkat etmelisiniz.Sağlıklı ve dengeli bir diyet sürdürmelisiniz.Vücutta meydana gelen değişikliklerle başa çıkmak için uygun giysiler seçmelisiniz.",
    "6.Ay Gebelik: Doktorunuzun izniyle hafif egzersiz yapmalısınız.Stresten uzak durmalı ve rahatlama tekniklerini uygulamalısınız.",
    "7.Ay Gebelik: Bebek büyümeye devam eder ve doğuma hazırlık yapar.Düzenli prenatal kontrollerinizi sürdürmelisiniz.Beslenmenize özen göstermeli, sağlıklı atıştırmalıklar tercih etmelisiniz.",
    "8.Ay Gebelik: Rahat bir uyku düzeni sağlamalısınız.Doğum planınızı yapmalı ve doğum öncesi eğitim almalısınız.Vücuttaki şişliklerin kontrol altında tutulması için aktivite seviyenizi düzenlemelisiniz.",
    "9.Ay Gebelik: Hamilelikte egzersiz yapmak için doktorunuzun önerilerine uymalısınız.Bebek hareketlerini takip etmeli ve herhangi bir anormallik durumunda doktorunuza danışmalısınız.",
    "1. Ay",
    "2. Ay",
    "3. Ay",
    "4. Ay",
    "5. Ay",
    "6. Ay",
    "7. Ay",
    "8. Ay",
    "9. Ay",
    "10. Ay",
    "11. Ay",
    "12. Ay",
    "13. Ay",
    "14. Ay",
    "15. Ay",
    "16. Ay",
    "17. Ay",
    "18. Ay",
    "19. Ay",
    "20. Ay",
    "21. Ay",
    "22. Ay",
    "23. Ay",
    "24. Ay",
  ];
}